export const BOOK_PATHS_FLOW = {
  start: {
    id: "start",
    kind: "style",
    style: null,
    title: "Choose a Style",
    body: "Start by choosing the historical tradition. Each step records your path and can be revised with Back/Restart.",
    images: ["26", "35", "37"],
    options: [
      { label: "Carolingian", next: "carolingian_board", set: { style: "Carolingian" } },
      { label: "Romanesque", next: "romanesque_board", set: { style: "Romanesque" } },
      { label: "Gothic", next: "gothic_board", set: { style: "Gothic" } },
    ],
  },

  carolingian_board: {
    id: "carolingian_board",
    kind: "step",
    style: "Carolingian",
    title: "Board Form",
    body: "Select the board edge profile used for this Carolingian reconstruction.",
    images: ["26", "27"],
    options: [
      { label: "Square board", next: "carolingian_channels", set: { board: "square" } },
      { label: "Bevelled board", next: "carolingian_channels", set: { board: "bevelled" } },
    ],
  },
  carolingian_channels: {
    id: "carolingian_channels",
    kind: "step",
    style: "Carolingian",
    title: "Board Channel Pattern",
    body: "Choose the board channel/attachment pattern.",
    images: ["33", "34"],
    options: [
      { label: "Pattern A", next: "carolingian_holes", set: { channels: "A" } },
      { label: "Pattern E", next: "carolingian_holes", set: { channels: "E" } },
    ],
  },
  carolingian_holes: {
    id: "carolingian_holes",
    kind: "step",
    style: "Carolingian",
    title: "Sewing Hole Preparation",
    body: "Select the hole preparation strategy for sewing stations.",
    images: ["8", "9", "10", "11"],
    options: [
      { label: "Pierced stations", next: "carolingian_changeover", set: { holes: "pierced" } },
      { label: "Cut stations", next: "carolingian_changeover", set: { holes: "cut" } },
    ],
  },
  carolingian_changeover: {
    id: "carolingian_changeover",
    kind: "step",
    style: "Carolingian",
    title: "Change-over Stations",
    body: "Define thread movement at head and tail stations.",
    images: ["21+22", "23+24"],
    options: [
      { label: "Link-stitch change-over", next: "carolingian_endleaf", set: { changeOver: "link" } },
      { label: "Span-stitch change-over", next: "carolingian_endleaf", set: { changeOver: "span" } },
    ],
  },
  carolingian_endleaf: {
    id: "carolingian_endleaf",
    kind: "step",
    style: "Carolingian",
    title: "Endleaf Construction",
    body: "Choose the endleaf strategy before lining and endbanding.",
    images: ["1+2", "3B", "2F"],
    options: [
      { label: "Integrated endleaf", next: "carolingian_lining", set: { endleaf: "integrated" } },
      { label: "Added endleaf", next: "carolingian_lining", set: { endleaf: "added" } },
    ],
  },
  carolingian_lining: {
    id: "carolingian_lining",
    kind: "step",
    style: "Carolingian",
    title: "Spine Lining",
    body: "Select a lining treatment for the spine.",
    images: ["39", "40"],
    options: [
      { label: "Patch lining", next: "carolingian_endband", set: { lining: "patch" } },
      { label: "Slotted lining", next: "carolingian_endband", set: { lining: "slotted" } },
    ],
  },
  carolingian_endband: {
    id: "carolingian_endband",
    kind: "step",
    style: "Carolingian",
    title: "Endband Program",
    body: "Choose how the endband is supported and finished.",
    images: ["47", "48", "52", "53"],
    options: [
      { label: "Unsupported endband", next: "carolingian_fastening", set: { endband: "unsupported" } },
      { label: "Supported endband", next: "carolingian_fastening", set: { endband: "supported" } },
    ],
  },
  carolingian_fastening: {
    id: "carolingian_fastening",
    kind: "step",
    style: "Carolingian",
    title: "Fastening Choice",
    body: "Finalize the Carolingian route with fastening details.",
    images: ["63", "69"],
    options: [
      { label: "Use Carolingian fastening", next: "carolingian_end", set: { fastening: "carolingian" } },
      { label: "No fastening", next: "carolingian_end", set: { fastening: "none" } },
    ],
  },
  carolingian_end: {
    id: "carolingian_end",
    kind: "end",
    style: "Carolingian",
    title: "Carolingian Path Complete",
    body: "This Carolingian branch is complete.",
    images: ["59"],
    options: [],
  },

  romanesque_board: {
    id: "romanesque_board",
    kind: "step",
    style: "Romanesque",
    title: "Board and Profile",
    body: "Choose a board profile for the Romanesque branch.",
    images: ["35", "36", "27"],
    options: [
      { label: "Romanesque 1A", next: "romanesque_support", set: { boardProfile: "1A" } },
      { label: "Romanesque 2C", next: "romanesque_support", set: { boardProfile: "2C" } },
    ],
  },
  romanesque_support: {
    id: "romanesque_support",
    kind: "step",
    style: "Romanesque",
    title: "Support Material",
    body: "Select the support material used in sewing.",
    images: ["12A", "13A", "14A"],
    options: [
      { label: "Slit leather thong", next: "romanesque_sewing", set: { support: "slit-leather" } },
      { label: "Double cord", next: "romanesque_sewing", set: { support: "double-cord" } },
      { label: "Twisted thong", next: "romanesque_sewing", set: { support: "twisted-thong" } },
    ],
  },
  romanesque_sewing: {
    id: "romanesque_sewing",
    kind: "step",
    style: "Romanesque",
    title: "Sewing Pattern",
    body: "Choose the dominant sewing pattern before composing final reconstruction.",
    images: ["15", "17", "19", "20"],
    options: [
      { label: "Herringbone", next: "romanesque_changeover", set: { sewing: "herringbone" } },
      { label: "Straight", next: "romanesque_changeover", set: { sewing: "straight" } },
      { label: "Packed straight", next: "romanesque_changeover", set: { sewing: "packed-straight" } },
    ],
  },
  romanesque_changeover: {
    id: "romanesque_changeover",
    kind: "step",
    style: "Romanesque",
    title: "Station Turnings",
    body: "Select turning behavior at head and tail stations.",
    images: ["21", "22", "23", "24", "84"],
    options: [
      { label: "Link stitch", next: "romanesque_endleaf", set: { changeOver: "link" } },
      { label: "Span stitch", next: "romanesque_endleaf", set: { changeOver: "span" } },
      { label: "Integral both ends", next: "romanesque_endleaf", set: { changeOver: "integral" } },
    ],
  },
  romanesque_endleaf: {
    id: "romanesque_endleaf",
    kind: "step",
    style: "Romanesque",
    title: "Endleaf Family",
    body: "Pick the endleaf family represented in this branch.",
    images: ["1", "2", "3C", "3D", "3E"],
    options: [
      { label: "Single folded endleaf", next: "romanesque_lining", set: { endleaf: "single" } },
      { label: "Wrapped endleaf", next: "romanesque_lining", set: { endleaf: "wrapped" } },
      { label: "Hooked endleaf", next: "romanesque_lining", set: { endleaf: "hooked" } },
    ],
  },
  romanesque_lining: {
    id: "romanesque_lining",
    kind: "step",
    style: "Romanesque",
    title: "Lining and Reinforcement",
    body: "Choose lining architecture before result composition.",
    images: ["39", "40", "85"],
    options: [
      { label: "Patch/slotted lining", next: "romanesque_result_select", set: { lining: "patch-slotted" } },
      { label: "Comb-dominant lining", next: "romanesque_result_select", set: { lining: "comb" } },
    ],
  },
  romanesque_result_select: {
    id: "romanesque_result_select",
    kind: "step",
    style: "Romanesque",
    title: "Composite Reconstruction",
    body: "Select the composite result to inspect. If the composite image is missing, components are shown automatically.",
    images: ["81", "82", "83"],
    options: [
      { label: "Composite 81", next: "romanesque_result_81", set: { compositeResult: "81" } },
      { label: "Composite 82", next: "romanesque_result_82", set: { compositeResult: "82" } },
      { label: "Composite 83", next: "romanesque_result_83", set: { compositeResult: "83" } },
    ],
  },
  romanesque_result_81: {
    id: "romanesque_result_81",
    kind: "step",
    style: "Romanesque",
    title: "Composite Result 81",
    body: "Result node built from selected Romanesque components.",
    compositeKey: "81",
    compositeOf: ["17", "12A", "21+22"],
    options: [{ label: "Continue", next: "romanesque_fastening" }],
  },
  romanesque_result_82: {
    id: "romanesque_result_82",
    kind: "step",
    style: "Romanesque",
    title: "Composite Result 82",
    body: "Result node built from selected Romanesque components.",
    compositeKey: "82",
    compositeOf: ["15", "12A", "21+22"],
    options: [{ label: "Continue", next: "romanesque_fastening" }],
  },
  romanesque_result_83: {
    id: "romanesque_result_83",
    kind: "step",
    style: "Romanesque",
    title: "Composite Result 83",
    body: "Result node built from selected Romanesque components.",
    compositeKey: "83",
    compositeOf: ["19", "14A", "21+22"],
    options: [{ label: "Continue", next: "romanesque_fastening" }],
  },
  romanesque_fastening: {
    id: "romanesque_fastening",
    kind: "step",
    style: "Romanesque",
    title: "Fastening Choice",
    body: "Finalize this branch with fastening evidence.",
    images: ["64", "69"],
    options: [
      { label: "Romanesque fastening", next: "romanesque_end", set: { fastening: "romanesque" } },
      { label: "No fastening", next: "romanesque_end", set: { fastening: "none" } },
    ],
  },
  romanesque_end: {
    id: "romanesque_end",
    kind: "end",
    style: "Romanesque",
    title: "Romanesque Path Complete",
    body: "This Romanesque branch is complete.",
    images: ["59"],
    options: [],
  },

  gothic_board: {
    id: "gothic_board",
    kind: "step",
    style: "Gothic",
    title: "Board Profile",
    body: "Choose a Gothic board profile and overall geometry.",
    images: ["37", "38", "26"],
    options: [
      { label: "Type B board", next: "gothic_support", set: { boardType: "B" } },
      { label: "Type C board", next: "gothic_support", set: { boardType: "C" } },
    ],
  },
  gothic_support: {
    id: "gothic_support",
    kind: "step",
    style: "Gothic",
    title: "Support Strategy",
    body: "Pick support material for Gothic sewing.",
    images: ["12A", "13A", "14A"],
    options: [
      { label: "Split leather", next: "gothic_sewing", set: { support: "split-leather" } },
      { label: "Double cord", next: "gothic_sewing", set: { support: "double-cord" } },
      { label: "Twisted thong", next: "gothic_sewing", set: { support: "twisted-thong" } },
    ],
  },
  gothic_sewing: {
    id: "gothic_sewing",
    kind: "step",
    style: "Gothic",
    title: "Sewing Pattern",
    body: "Select the dominant sewing pattern.",
    images: ["16", "19", "20"],
    options: [
      { label: "Herringbone", next: "gothic_stations", set: { sewing: "herringbone" } },
      { label: "Straight", next: "gothic_stations", set: { sewing: "straight" } },
    ],
  },
  gothic_stations: {
    id: "gothic_stations",
    kind: "step",
    style: "Gothic",
    title: "Station Evidence",
    body: "Review head/tail station behavior.",
    images: ["21+22", "23+24", "86"],
    options: [
      { label: "Link-stitch station", next: "gothic_endband", set: { stations: "link" } },
      { label: "Span-stitch station", next: "gothic_endband", set: { stations: "span" } },
    ],
  },
  gothic_endband: {
    id: "gothic_endband",
    kind: "step",
    style: "Gothic",
    title: "Endband Type",
    body: "Choose the endband and tab profile.",
    images: ["86", "87", "52", "53"],
    options: [
      { label: "No endtab", next: "gothic_cover", set: { endband: "none" } },
      { label: "Square tab", next: "gothic_cover", set: { endband: "square" } },
      { label: "Round tab", next: "gothic_cover", set: { endband: "round" } },
    ],
  },
  gothic_cover: {
    id: "gothic_cover",
    kind: "step",
    style: "Gothic",
    title: "Cover/Corners",
    body: "Select corner and perimeter sewing treatment.",
    images: ["55", "56", "57", "59"],
    options: [
      { label: "Perimeter-sewn corners", next: "gothic_fastening", set: { cover: "perimeter" } },
      { label: "Mitred corners", next: "gothic_fastening", set: { cover: "mitred" } },
      { label: "Overcover", next: "gothic_fastening", set: { cover: "overcover" } },
    ],
  },
  gothic_fastening: {
    id: "gothic_fastening",
    kind: "step",
    style: "Gothic",
    title: "Fastening Family",
    body: "Finalize with regional fastening evidence.",
    images: ["65", "66", "67", "88", "69"],
    options: [
      { label: "English", next: "gothic_end", set: { fastening: "english" } },
      { label: "German", next: "gothic_end", set: { fastening: "german" } },
      { label: "Dutch", next: "gothic_end", set: { fastening: "dutch" } },
    ],
  },
  gothic_end: {
    id: "gothic_end",
    kind: "end",
    style: "Gothic",
    title: "Gothic Path Complete",
    body: "This Gothic branch is complete.",
    images: ["69"],
    options: [],
  },
};
